package com.example.mynewwords.utils

object MyStringObjects {
    val FIRST_ENTER_MODE:String="FIRST_ENTER_MODE_MY_DICTIONARY_SMT"
    val LANGUAGE_ONE:String="LANGUAGE_ONE_MY_DICTIONARY_SMS"
    val LANGUAGE_TWO:String="LANGUAGE_TWO_MY_DICTIONARY_SMS"
    val DAY_NIGHT:String="DAY_NIGHT_MY_DICTIONARY_SMT"
    val DICTIONARY_ID_MOVE="DICTIONARY_ID_MOVE_MY_DICTIONARY_SMT"
}